controller_manager:
  ros__parameters:
    update_rate: 100

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # gripper_controller:
    #   type: gripper_controller/GripperController

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position

    state_interfaces:
      - position
      # - velocity
      # - effort

    open_loop_control: true
    allow_integration_in_goal_trajectory: true

# gripper_controller:
#   ros__parameters:
#     joints:
#       - gripper_left_joint
#       - gripper_right_joint
#     gripper_type: "left"
