controller_manager:
  ros__parameters:
    update_rate: 50 # Hz
    use_sim_time: false

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      # type: position_controllers/GripperActionController
      type: parallel_gripper_action_controller/GripperActionController
      # type: forward_command_controller/ForwardCommandController

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
      # - effort

    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    interpolate_from_desired_state: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

    # open_loop_control: true
    # allow_integration_in_goal_trajectory: true

gripper_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: false
    goal_tolerance: 0.01
    max_effort: 0.0
    stall_timeout: 1.0
    stall_velocity_threshold: 0.001
    joint: gripper_left_joint
    # state_interfaces:
    #   - position
    #   - velocity
    # command_interfaces:
    #   - position
    # conversion_factor: 0.0001
