controller_manager:
  ros__parameters:
    update_rate: 10  # High-quality industrial arms update fast (100Hz or even 500Hz)

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

  arm_controller:
    ros__parameters:
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
      command_interfaces:
        - position
      state_interfaces:
        - position
      # state_publish_rate: 50.0  # How fast the controller publishes states
      # action_monitor_rate: 20.0  # How often it monitors goals

      # allow_partial_joints_goal: true
      open_loop_control: true
      allow_integration_in_goal_trajectory: true
      # interpolation_method: splines

joint_state_broadcaster:
  ros__parameters: {}
