controller_manager:
  ros__parameters:  # Use ros__parameters consistently
    # In ROS2 control, write() is called at every control loop cycle, update_rate.
    update_rate: 10

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:  # This top-level definition is likely not intended
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position
    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectory: true