controller_manager:
  ros__parameters:
    update_rate: 10  # update_rate specifies how often (in Hz) the controllers should be updated.

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 5  # Hz
arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity
    joint_limits:
      joint1:
        min_position: -1.98
        max_position: 1.98
      joint2:
        min_position: -1.41
        max_position: 1.34
      joint3:
        min_position: -3.14
        max_position: 1.22
      joint4:
        min_position: -3.14
        max_position: 3.14
      joint5:
        min_position: -2.42
        max_position: 2.42
      joint6:
        min_position: -3.14
        max_position: 3.14
    open_loop_control: true
    allow_integration_in_goal_trajectory: true

